version: '3.7'

services:
  catalogdb:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

  basketdb:
    image: redis:alpine

  discont.api:
    image: ${DOCKER_REGISTRY-}discontapi
    build:
      context: .
      dockerfile: Discont.API/Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.GRPC/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:

